### ISSUE TITLE
audio support

### ISSUE THREAD

**Issue by faugeh** [godka/node-rtsp-live555#1]
How can i make audio stream work as well?
When i change hasAudio in 
`https://github.com/godka/node-rtsp-live555/blob/master/example/html/dist/core.js` line 97
to true, even the video no longer is rendered in the browser. However no errors occur in flv-player (dev tools of browser indicate that everything is working fine). Also, only the video stream is recognised by the flv player. Do i need to make other changes or is audio not supported?

**Comment by godka** [comment]
Hi!
Thanks for your interest! Unfortunately,audio has not been supported in live555/c++ kernel yet.
See https://github.com/godka/node-rtsp-live555/tree/master/lib/extras/src
To make audio stream work,you should see mythRTSP.cpp,in src folder,and goto line 160
```
// Having successfully setup the subsession, create a data sink for it, and call "startPlaying()" on it.
		// (This will prepare the data sink to receive data; the actual flow of data from the client won't start happening until later,
		// after we've sent a RTSP "PLAY" command.)
		if (strcmp(scs.subsession->mediumName(), "video") == 0 && strcmp(scs.subsession->codecName(), "H264") == 0) {
			scs.subsession->sink = H264VideoStreamSink::createNew(env, scs.responsehandler, scs.responseData);
		}
```

If you  wanna add audio support,try to write AACStreamSink based on DummySink.A simple sample is shown in my bro's repo.
```
https://github.com/aesirteam/proxyRepeater/blob/master/src/rtmpPusher.cpp
```
 I'll update my code long before.
