### ISSUE TITLE
How to use it with flv.js

### ISSUE THREAD

**Issue by dpmaycry** [godka/node-rtsp-live555#2]
Is there a guide or something?

**Comment by godka** [comment]
Hi, thanks for watching my work.
The flv.js example is shown in 
https://github.com/godka/node-rtsp-live555/blob/6e84a1c310f60a95010377d0482fd97d0139d247/example/html/dist/core.js#L89

**Comment by RamaTheTrainer** [comment]
First Appreciate U r Work .  Hi Can u provide Detailed Documentation to use the Package ...??

**Comment by godka** [comment]
> First Appreciate U r Work . Hi Can u provide Detailed Documentation to use the Package ...??

Sorry for the long delay (really long).
We will write the docs later on.
