### ISSUE TITLE
Work perfectly on MacOS, but Ubuntu and CentOS

### ISSUE THREAD

**Issue by linwenchao** [godka/node-rtsp-live555#3]

**Comment by godka** [comment]
Hi bro, thanks to following my work!
Do you mean the work doesn't work on the Linux?
Maybe you can make the "bin" file manually, and the source code is in:
https://github.com/godka/node-rtsp-live555/blob/master/lib/extras/src/Makefile
For the Linux platform, we provide three pre-build cores including 'arm', 'x86' and 'x64' as described in:
https://github.com/godka/node-rtsp-live555/tree/master/lib/extras/linux

**Comment by linwenchao** [comment]
Hi @godka , 看资料发现是同胞，握爪微笑 :)
我看到有编译好的包，我指的是，在Linux上运行时，console中flv.js会不断报错
[MSEController] > failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null

[见 https://github.com/Bilibili/flv.js/issues/256 ](https://github.com/Bilibili/flv.js/issues/256)

播了几帧然后就停止播放了
开始怀疑是flv.js的问题，但试过替换成其它FLV源（例如bilibili的），不会报错停止。
所以，估计有可能是streaming server的问题

**Comment by godka** [comment]
OK, got it.
I have also met the same issue when I am writing this work. I guess if flv.js did not receive a new video stream in a short timespan(less than 500ms), it would decide to tear down the video session immediately. Before the official solution publishes, I will use a simple clock which monitors the video session and ready to reconnect to tackle this problem.

**Comment by pattarmanjunath50** [comment]
Hi,
How can I use this in my angular 2 application?

**Comment by godka** [comment]
> Hi,
> How can I use this in my angular 2 application?

Hi, thanks for watching my work.
In fact, I know little about angular 2. This work relies on javascript only, and I guess rtsp-live555 can work well in your application.
